Blog de Insectos/Controllers/PageController.cs
using Blog_de_Insectos.Data;
using Blog_de_Insectos.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Blog_de_Insectos.Controllers
{
    public class PageController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PageController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> About()
        {
            var page = await _context.Pages!.FirstOrDefaultAsync(x => x.Slug == "about");
            var vm = new PageVM()
            {
                Title = page!.Title,
                ShortDescription = page.ShortDescription,
                Description = page.Description,
                ThumbnailUrl = page.ThumbnailUrl,
            };
            return View(vm);
        }

        public async Task<IActionResult> Contact()
        {
            var page = await _context.Pages!.FirstOrDefaultAsync(x => x.Slug == "contact");
            var vm = new PageVM()
            {
                Title = page!.Title,
                ShortDescription = page.ShortDescription,
                Description = page.Description,
                ThumbnailUrl = page.ThumbnailUrl,
            };
            return View(vm);
        }

        public async Task<IActionResult> PrivacyPolicy()
        {
            var page = await _context.Pages!.FirstOrDefaultAsync(x => x.Slug == "privacy");
            var vm = new PageVM()
            {
                Title = page!.Title,
                ShortDescription = page.ShortDescription,
                Description = page.Description,
                ThumbnailUrl = page.ThumbnailUrl,
            };
            return View(vm);
        }
    }
}

Blog de Insectos/Areas/Admin/Views/Page/About.cshtml
@model Blog_de_Insectos.ViewModels.PageVM

@{
    ViewData["Title"] = "About Page";
}

<div class="container-fluid">
    <a class="btn btn-primary mb-1" asp-action="Index" asp-controller="Post">Go Back</a>
    <div class="card">
        <div class="card-header bg-primary">
            <h4 class="card-title text-white">About Page</h4>
        </div>
        <div class="card-body">
            <form asp-action="About" asp-controller="Page" asp-area="Admin" enctype="multipart/form-data">
                <input type="hidden" asp-for="Id" />
                <input type="hidden" asp-for="ThumbnailUrl" />
                <div class="row mb-2">
                    <div class="col-9">
                        <div class="mb-2">
                            <label>Title</label>
                            <input type="text" asp-for="Title" class="form-control" />
                            <span asp-validation-for="Title" class="text-danger"></span>
                        </div>
                        <div class="mb-2">
                            <label>Short Description</label>
                            <input type="text" asp-for="ShortDescription" class="form-control" />
                            <span asp-validation-for="ShortDescription" class="text-danger"></span>
                        </div>
                        <div class="mb-2">
                            <label>Description</label>
                            <textarea id="richEditor" asp-for="Description" class="form-control" rows="8"></textarea>
                            <span asp-validation-for="Description" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-3">
                        <div class="mb-2">
                            @{
                                if (Model.ThumbnailUrl == null)
                                {
                                    <img src="~/thumbnails/default_image.png" class="img-fluid" id="thumbnail" />
                                }

                                else
                                {
                                    <img src="~/thumbnails/@Model.ThumbnailUrl" class="img-fluid" id="thumbnail" />

                                }
                            }
                        </div>
                        <div class="mb-2">
                            <label>Thumbnail</label>
                            <input type="file" asp-for="Thumbnail" class="custom-file" />
                            <span asp-validation-for="Description" class="text-danger"></span>
                        </div>
                    </div>
                </div>

                <div class="mb-2">
                    <button type="submit" class="btn btn-primary w-100">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
    <script>
        $(".custom-file").on("change", function () {
            var fileName = $(this).val().split("\\").pop();
            $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
            document.getElementById('thumbnail').src = window.URL.createObjectURL(this.files[0])
        });
    </script>
}

Blog de Insectos/Areas/Admin/Views/Page/Contact.cshtml
@model Blog_de_Insectos.ViewModels.PageVM

@{
    ViewData["Title"] = "About Page";
}

<div class="container-fluid">
    <a class="btn btn-primary mb-1" asp-action="Index" asp-controller="Post">Go Back</a>
    <div class="card">
        <div class="card-header bg-primary">
            <h4 class="card-title text-white">Contact Page</h4>
        </div>
        <div class="card-body">
            <form asp-action="Contact" asp-controller="Page" asp-area="Admin" enctype="multipart/form-data">
                <input type="hidden" asp-for="Id" />
                <input type="hidden" asp-for="ThumbnailUrl" />
                <div class="row mb-2">
                    <div class="col-9">
                        <div class="mb-2">
                            <label>Title</label>
                            <input type="text" asp-for="Title" class="form-control" />
                            <span asp-validation-for="Title" class="text-danger"></span>
                        </div>
                        <div class="mb-2">
                            <label>Short Description</label>
                            <input type="text" asp-for="ShortDescription" class="form-control" />
                            <span asp-validation-for="ShortDescription" class="text-danger"></span>
                        </div>
                        <div class="mb-2">
                            <label>Description</label>
                            <textarea id="richEditor" asp-for="Description" class="form-control" rows="8"></textarea>
                            <span asp-validation-for="Description" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-3">
                        <div class="mb-2">
                            @{
                                if (Model.ThumbnailUrl == null)
                                {
                                    <img src="~/thumbnails/default_image.png" class="img-fluid" id="thumbnail" />
                                }

                                else
                                {
                                    <img src="~/thumbnails/@Model.ThumbnailUrl" class="img-fluid" id="thumbnail" />

                                }
                            }
                        </div>
                        <div class="mb-2">
                            <label>Thumbnail</label>
                            <input type="file" asp-for="Thumbnail" class="custom-file" />
                            <span asp-validation-for="Description" class="text-danger"></span>
                        </div>
                    </div>
                </div>

                <div class="mb-2">
                    <button type="submit" class="btn btn-primary w-100">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
    <script>
        $(".custom-file").on("change", function () {
            var fileName = $(this).val().split("\\").pop();
            $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
            document.getElementById('thumbnail').src = window.URL.createObjectURL(this.files[0])
        });
    </script>
}